[package]
name = "remote-point-calculator"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/jackwickham/furthest-point-calculator"
license = "MIT"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.83"
